### ISSUE TITLE
Create Customer Account Screen

### ISSUE THREAD

**Issue by michaelpropp18** [michaelpropp18/universal_store#10]
Finish the customer "create your account" screen. You can re-use the input_field and submit_button widgets I used in the login screen or create your own. 
- [x] Create fields for first name, last name, email, password, and re-enter password
- [x] Add button to register and button to go back
- [x] Add error handling if the user enters invalid entries.
- [x] Add the background_gradient widget (see sign-in screen to see how to do this)

**Comment by saahmed2** [comment]
Hi Michael, I'd like to ask if you've completed this. I would like to have a crack at it. Let me know, thanks.
