### ISSUE TITLE
Secure Firebase Rules

### ISSUE THREAD

**Issue by michaelpropp18** [michaelpropp18/universal_store#21]
Add secure firebase rules for read/write privileges to database. Currently anyone on the internet could view, edit, and delete entires in our db (which isn't an issue now since there's nothing substantial, but is a security vulnerability once we have users). https://firebase.google.com/docs/rules/basics has a good description.

**Comment by aaronanderson99** [comment]
Each customer has a file in the 'customers' directory. Currently set rules to allow only the user to read and write to their own file (A similar rule will follow for stores when that functionality is implemented). Will continue to update as development progresses and needs change.
