### ISSUE TITLE
As a registered user who has forgotten my login information, I want to reset my account so that I can regain access to it.

### ISSUE THREAD

**Issue by michaelpropp18** [michaelpropp18/universal_store#7]
Implement a forgot password mechanism on the sign in screen. This has a lot of steps so feel free to reach out to Michael if you need help. 

- [ ] Backend: Implement a function in auth.dart that sends an email with instructions to generate a new password. This is something firebase probably does. This function should be async and should return an AuthResultStatus indicating the status of the request (successful or error). You might need to add a new status in auth_exception_handler.dart. 
- [x] Backend: Create a new function in the login viewModel that will then call the auth.dart function and perform any additional changes to the viewModel.
- [x] Frontend: Create a new screen with a forgot password text input and submit button. You will need to add the route to router.dart. 
- [x] Frontend: Create a pop-up message to indicate whether a password request was sent. This pop-up should have a return button that brings the user back to the home screen. You can do this using a navigator.pop() call. 
- [x] Frontend: Set the forgot password button on the sign in screen to call the viewModel forgot password function and perform a navigator.pushNamed() to navigate to the forgot password screen.

**Comment by nmook0413** [comment]
nate- frontend

**Comment by michaelpropp18** [comment]
brandon- backend

**Comment by aaronanderson99** [comment]
note for backend:
The password reset email is a built-in feature of firebase authentication (firebase.auth.sendPasswordResetEmail(emailAddress) method), you can just throw these lines in:
(from google's firebase docs)

var auth = firebase.auth();
var emailAddress = "user@example.com";

auth.sendPasswordResetEmail(emailAddress).then(function() {
  // Email sent.
}).catch(function(error) {
  // An error happened.
});
